### ISSUE TITLE
Counter lässt sich Manipulieren

### ISSUE THREAD

**Issue by DagobertDaring** [Szuuuken/evc#5]
ac8d6584b6d4955754a2ad3236b1391e29e24084
Beantwortet man bei einer Frage mit der Maus richtig, so lässt sich auf vermehrtes betätigen der Leertaste der Counter manipulieren.

auf Firefox 45.2.0 ESR

**Comment by Szuuuken** [comment]
Ich habe das Problem mit dem neuem Update gelöst ( ich habe die Seite komplett neu gebaut ).
