### ISSUE TITLE
Keyboard Shortcuts funktionieren nicht

### ISSUE THREAD

**Issue by DagobertDaring** [Szuuuken/evc#6]
ac8d6584b6d4955754a2ad3236b1391e29e24084
lassen sich die Keyboard Shortcuts nicht verwenden.
auf Firefox 45.2.0 ESR

**Comment by Szuuuken** [comment]
Ich habe das Problem mit dem neuem Update gelöst ( ich habe die Seite komplett neu gebaut ).
