### ISSUE TITLE
Neue Fragen hinzufügen 

### ISSUE THREAD

**Issue by ghost** [Szuuuken/evc#9]
Servus,
ich schlage vor, folgende Fragen hinzufügen:
Beim Environment Mapping wird die exakte Reflexionsrichtung für die Schattierung verwendet. - F (Globale Beleuchtung & Texturen)
Beim Bump-Mapping ändert sich die Geometrie nicht, lediglich die Oberflächennormale wird geändert. - W (Globale Beleuchtung & Texturen)
Die Hermite-Interpolation erfolgt mit Polynomen welchen Grades? (A) Ersten - F (B) Zweiten - F (C) Dritten - W (Kurven & Flächen)
Danke sehr!
MfG

**Comment by Szuuuken** [comment]
Hi,
danke für deinen Vorschlag.
Bitte erstell einen neuen pull request der die neuen Fragen hinzufügt.

lg Daniel
